MCU			 = atmega328p
ARDUINO_LIBS = 
#USER_LIBS = Monitor Wire DS2482
USER_LIBS = LiquidCrystal
USER_LDFLAGS = -u,vfprintf -lprintf_flt -lm
#USER_LDFLAGS = -u,vfprintf -lprintf_min -lm
AVRDUDE_PROGRAMMER  = arduino
AVRDUDE_BAUDRATE = 57600
include ../../arduino/Arduino.mk